### PR TITLE
set proper target name

### PR DESCRIPTION
**Pull request by matej-vavrek**
#146 set proper target name for Target in header bar

### CODE REVIEW

**Comment by reskyner** [comment]
Hi Matej,

Can you open a pull request for this into our master branch, please?

**Comment by zemiacsik** [comment]
Sure!

**Comment by matej-vavrek** [comment]
Sure!

**Comment by matej-vavrek** [comment]
@reskyner I did it from master because it contains another valuable fix: https://github.com/xchem/fragalysis-frontend/pull/143

**Pull request merged**
